### PR TITLE
Editorial: Missing definitive article

### PR DESCRIPTION
**Pull request by snuggs**
Noticed when linked from description in https://github.com/whatwg/dom/issues/478

References:
  - https://github.com/whatwg/dom/blob/master/dom.bs#L2327
  - https://github.com/whatwg/dom/blob/master/dom.bs#L2408
  - https://github.com/whatwg/dom/blob/master/dom.bs#L2514
  - https://github.com/whatwg/dom/blob/master/dom.bs#L3806
  - https://github.com/whatwg/dom/blob/master/dom.bs#L5070
  - https://github.com/whatwg/dom/blob/master/dom.bs#L5300
  - https://github.com/whatwg/dom/blob/master/dom.bs#L5655

***
<a href="https://whatpr.org/dom/834.html" title="Last updated on Feb 12, 2020, 4:47 PM UTC (80c7a47)">Preview</a> | <a href="https://whatpr.org/dom/834/de29633...80c7a47.html" title="Last updated on Feb 12, 2020, 4:47 PM UTC (80c7a47)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Thanks, would you like to add yourself to the Acknowledgments section?

**Comment by snuggs** [comment]
> Thanks, would you like to add yourself to the Acknowledgments section?
@annevk been there done that _(thanks to you)_ 😄 
I have been using my first name since my Mother passed over the holiday. Ra'Shaun is my middle name. Updated in 180cac7.

That said...I was going to change the previous person's acknowledgement as it looks like something funky went on at the tail end. However didn't feel I had right to touch someone else's. I crossed my fingers and attempted to blame `dom.bs` but takes so long github says _"taking too long to load"_. I've always gotten this but never bought it up. I digress.

Should we just leave it alone?

**Comment by annevk** [comment]
Yeah, leave that one alone, but you want to resort yours.

**Comment by snuggs** [comment]
@annevk ok what left needs to be done? Says needs to be merged by someone else.
I know you have better things to do. :-)

Thank you so much!

**Comment by annevk** [comment]
Well, the Acknowledgments section is sorted on the (overall) name and you changed your name, but not how it's sorted.

**Comment by snuggs** [comment]
@annevk AHH RE-sort...Was thinking 🌴resort🌴.
I need a vacation. Should be good now. Thanks!

**Pull request merged**
