### PR TITLE
Define ParentNode#replaceChildren

### LINKED ISSUE #478: Proposal: ParentNode.replaceAll() / ParentNode.replaceChildren()
The **ParentNode.replaceAll()** or **ParentNode.replaceChildren()** method would remove all child nodes from the ParentNode while allowing the insertion of a new set of nodes. The best name is yet settled upon.

A “replace all” concept [already exists](https://dom.spec.whatwg.org/#concept-node-replace-all) in the spec.

### Syntax

```
ParentNode.replaceAll();
ParentNode.replaceChildren();
```

### Example:

1. In a form, changing a **Country** `<select>` causes options to change in a corresponding **Region** `<select>`:

```js
countrySelectElement.addEventListener('change', () => {
  regionSelectElement.replaceAll(...optionElementsById[countrySelectElement.value]);
});
```

2. Any time an element is to be emptied.

```js
elementToBeEmptied.replaceChildren();
```

### Rationale:

Like `append()`, `prepend()`, `before()`, `after()`, and `replaceWith()`, we’re allowing developers to do something useful without a loop, e.g:

```js
// remove all child nodes from the ParentNode
while (parentNode.lastChild) {
  parentNode.removeChild(parentNode.lastChild);
}

// insert a new set of Node objects or DOMString objects
parentNode.append(...addedNodes);
```

### Fallback Strategies

There are 2 common strategies to empty a ParentNode before inserting a new set of nodes (using [`ParentNode.append`](https://dom.spec.whatwg.org/#dom-parentnode-append)).

The 1st strategy is to erase the innerHTML of a ParentNode. This is less meaningful and leads one to question the underlying implementation.

```js
ParentNode.innerHTML = ''
```

The 2nd strategy is to loop over and remove each child of the ParentNode. This is verbosE and leads one to wish for the same loop-free “sugar” provided to `append()`, `prepend()`, `before()`, `after()`, and `replaceWith()`.

```
while (parentNode.lastChild) {
  parentNode.removeChild(parentNode.lastChild);
}
```

---

## Previous proposal (replaceAll)

> A previous proposal named this method `replaceAll`, a name that mirrors a section in the spec. Recent feedback has been that `replaceChildren` would be a more accurate and less confusing name. Therefore, both are represented in this proposal.

---

## Original Proposal (empty)

> The original proposal’s functionality is fully captured in the updated proposal. The updated proposal also reflects an existing concept in the spec.

The **ParentNode.empty()** method would remove all child nodes from the parent node.

### Syntax

```
ParentNode.empty();
```

### Example:

In a filtering component, a change to one `<select>` swaps out the `<option>` elements available to a second `<select>`:

```js
selectEl1.addEventListener('change', () => {
  selectEl2.empty();

  selectEl2.append(...optionElsByValue[selectEl1.value]);
});
```

### Rationale:

Like `append()`, `prepend()`, `before()`, `after()`, and `replaceWith()`, we’re allowing developers to do something useful without a loop, e.g:

```js
while (parentNode.lastChild) {
  parentNode.removeChild(parentNode.lastChild);
}
```

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #478 

Closes #755, closes #835.

Tests: https://github.com/web-platform-tests/wpt/pull/22524

Implementation bugs:
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=198578
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1626015

***
<a href="https://whatpr.org/dom/851.html" title="Last updated on Apr 20, 2020, 3:52 PM UTC (a58ce1d)">Preview</a> | <a href="https://whatpr.org/dom/851/61834f7...a58ce1d.html" title="Last updated on Apr 20, 2020, 3:52 PM UTC (a58ce1d)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Thanks @saschanaz! This change looks good, to me, but we'll need to address the remaining bits from https://whatwg.org/working-mode#changes, in particular tests.

Implementation bugs: https://bugs.webkit.org/show_bug.cgi?id=198578, ?
Tests: ?
Support: I think Firefox and Safari can be considered to be supportive. @mfreed7 thoughts for Chrome?

**Comment by annevk** [comment]
@domenic @TimothyGu any interest in writing a jsdom implementation? I wonder if we should start "soft" requiring that for additions to the DOM Standard to add another layer of certainty with regards to the algorithms.

**Comment by mfreed7** [comment]
FYI, Chromium plans to try to get this implemented in Q2.

**Comment by annevk** [comment]
Thanks @saschanaz for writing all the tests and the change to the DOM Standard and Olli for reviewing! Great work.

**Pull request merged**
