### PR TITLE
Add toggleAttribute to Element.

### PR DESCRIPTION
**Pull request by jonathanKingston**
See https://github.com/whatwg/dom/issues/461 for details.

***
<a href="https://whatpr.org/dom/656.html" title="Last updated on Jun 21, 2018, 8:40 AM GMT (1a12e27)">Preview</a> | <a href="https://whatpr.org/dom/656/c69d7c0...1a12e27.html" title="Last updated on Jun 21, 2018, 8:40 AM GMT (1a12e27)">Diff</a>

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Tests are in the Firefox Implementation: https://phabricator.services.mozilla.com/D1710
Servo PR: https://github.com/servo/servo/pull/21074
I can file the bugs on other browsers when we have a specification link.

**Comment by annevk** [comment]
@jonathanKingston typically we file implementation bugs with links to the PR before the PR has landed. So you should feel free to go ahead with that.

Let me know if the changes I made are okay and we can land afterwards then.

**Comment by jonathanKingston** [comment]
Browser bugs (am I missing any?):
https://bugs.chromium.org/p/chromium/issues/detail?id=854960
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17981545/
https://bugs.webkit.org/show_bug.cgi?id=186883

I can do a word for word comparison later if concerned however I was only concerned with the steps moving around.
Thanks, all the commits look fine so long as it's purely wording / spacing nits?
- Ordering changes
- Spacing and indenting
- Removal of "Otherwise"

**Comment by annevk** [comment]
Yeah, that was it, thanks!

**Pull request merged**
