### PR TITLE
Mark dependent abort signals as aborted before firing events

### LINKED ISSUE #1293: AbortSignal.any() assertion failure
### What is the issue with the DOM Standard?

In Gecko [Bug 1903676](https://bugzilla.mozilla.org/show_bug.cgi?id=1903676), a test case was found where the assertion in [create a dependent abort signal](https://dom.spec.whatwg.org/#create-a-dependent-abort-signal) step 4.2.1. does not hold. I believe this is a spec issue.

Here is the example
```
let a = new AbortController();
let b = AbortSignal.any([a.signal]);
a.signal.addEventListener("abort", () => {
  AbortSignal.any([b]);
  console.log(b.aborted, a.signal.aborted);  // false, true
})
a.abort();
```
During the abort event of `a`, we create a dependent signal from `b`, which is not yet aborted. If `b` is not aborted and dependent on `a`, the spec expects `a` to be not aborted too and asserts this. The problem is that [signal abort](https://dom.spec.whatwg.org/#abortsignal-signal-abort) fires the event before aborting the dependent signals, steps 5 and 6 of signal abort could be switched to resolve this issue.

@shaseley

### PR DESCRIPTION
**Pull request by shaseley**
The assert in 4.2.1 of "create a dependent abort signal" fails when creating a dependent signal while dispatching abort events or running abort algorithms if abort had not yet been propagated to one of the sources.

This fix splits "signal abort" into two phases: first, set the abort reason on the signal being aborted and all of its unaborted dependents; next, run the abort algorithms and dispatch events for the signal and those same dependents. Note that:
 1. Dependent signals do not themselves have dependent signals, which means it's unnecessary to recursively call "signal abort"
 2. This approach retains the existing event dispatch order, while ensuring the abort state is synced before any JS runs

This fixes #1293.

---

- [x] At least two implementers are interested (and none opposed):
   * Chromium
   * WebKit
- [x] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at: https://github.com/web-platform-tests/wpt/pull/47653
- [x] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chromium: https://issues.chromium.org/issues/361129283
   * Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1903676
   * WebKit: https://bugs.webkit.org/show_bug.cgi?id=278159
   * Deno (only for aborting and events): https://github.com/denoland/deno/issues/25118
   * Node.js (only for aborting and events): https://github.com/nodejs/node/issues/54466
- [x] [MDN issue](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) is filed: N/A, bug fix
- [x] The top of this comment includes a [clear commit message](https://github.com/whatwg/meta/blob/main/COMMITTING.md) to use. 

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/dom/1295.html" title="Last updated on Aug 20, 2024, 8:57 PM UTC (0d05525)">Preview</a> | <a href="https://whatpr.org/dom/1295/7c494e5...0d05525.html" title="Last updated on Aug 20, 2024, 8:57 PM UTC (0d05525)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I wonder if @domenic / @jakearchibald / @jasnell are willing to review this?

Does this require implementation changes or a test?

**Comment by jasnell** [comment]
Seems fine to me

**Comment by shaseley** [comment]
> Does this require implementation changes or a test?

Yes to both. WIP tests are [here](https://chromium-review.googlesource.com/c/chromium/src/+/5664649/1/third_party/blink/web_tests/external/wpt/dom/abort/resources/abort-signal-any-tests.js#193). I was holding off on landing that and filing bugs until someone had a chance to take a first pass on the PR.

**Review by domenic — APPROVED** [review]

**Comment by annevk** [comment]
Since this is fixing a bug, feel free to count WebKit as interested.

@vinhill thoughts?

**Comment by maraisr** [comment]
Just created related WebKit bug issue: https://bugs.webkit.org/show_bug.cgi?id=278159. Will be ready to land if not landed over the weekend.

**Comment by vinhill** [comment]
I'm no longer employed at Mozilla, but they are likely interested due to [Bug 1903676](https://bugzilla.mozilla.org/show_bug.cgi?id=1903676)
@saschanaz

**Comment by annevk** [comment]
@shaseley from my perspective this is good to land, modulo checking the checkboxes in OP.

**Comment by saschanaz** [comment]
LGTM from Mozilla. We can reuse https://bugzilla.mozilla.org/show_bug.cgi?id=1903676 as an implementation bug.

**Comment by shaseley** [comment]
@annevk bugs filed and checkboxes updated!

**Comment by domfarolino** [comment]
I just came across this after looking into the AbortSignal algorithms while working on Observables, and I don't understand this part:

> Dependent signals do not themselves have dependent signals, which means it's unnecessary to recursively call "signal abort"

Why is this true? In Observables, we were using dependent `AbortSignal`s for a while, for each signal that was used to subscribe to upstream Observables, and I believe we were able to create a long chain of `AbortSignal` dependencies such that aborting some initial signal led to the recursive invocation of (old version of) the "**signal abort**" algorithm, on a whole deep chain of signals. Why does this PR say that is not possible?

Note: We are no longer chaining dependent signals like this in Observables, because the timing of aborting parent signals before dependents did not work for us (https://github.com/WICG/observable/pull/154), but still I think it is very possible to do, no?

**Pull request merged**
