### PR TITLE
Introduce abortSignal.throwIfAborted()

### LINKED ISSUE #927: Encourage use of AbortError for cancellation?
Bit of a half baked idea, but should we make it easier to throw abort errors from signals? Something like:

```js
AbortSignal.prototype.assertNotAborted = function(message = 'Aborted') {
  if (this.aborted) throw new DOMException(message, 'AbortError');
};
```

I know it's a one-liner, but it might encourage using the right kind of error?

### PR DESCRIPTION
**Pull request by domenic**
Closes #927.

- [x] At least two implementers are interested (and none opposed):
   * Chromium
   * Gecko
- [x] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * https://github.com/web-platform-tests/wpt/pull/31947
- [x] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1273458
   * Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1745372
   * Safari: https://bugs.webkit.org/show_bug.cgi?id=234127

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/dom/1034.html" title="Last updated on Dec 10, 2021, 8:37 AM UTC (0645ef6)">Preview</a> | <a href="https://whatpr.org/dom/1034/982c7e2...0645ef6.html" title="Last updated on Dec 10, 2021, 8:37 AM UTC (0645ef6)">Diff</a>

### CODE REVIEW

**Review by annevk — APPROVED** [review]

**Comment by josepharhar** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1273458

**Review by jasnell — APPROVED** [review]
This will be helpful to save some boilerplate. +1

**Comment by domenic** [comment]
Awesome :). If we can take Mozilla as interested per @annevk's enthusiasm, then this is ready to merge as soon as someone writes tests.

**Comment by jasnell** [comment]
@domenic .. WPT test PR here: https://github.com/web-platform-tests/wpt/pull/31947

**Comment by domenic** [comment]
Tests are merged; merge at will @annevk!

**Comment by cdumez** [comment]
Should probably be added to web-platform-tests/interfaces/dom.idl too.

**Comment by annevk** [comment]
@cdumez that should happen automatically through a bot, but it might take a day or so.

**Comment by jasnell** [comment]
PR landed in node.js! support will roll out in the next 17.x release

**Pull request merged**
