### PR TITLE
Add legacyOutputDidListenersThrowFlag to event dispatch for IDB

### PR DESCRIPTION
**Pull request by annevk**
Indexed Database API could have done with some architectural design
review.

See https://github.com/w3c/IndexedDB/issues/140 for context.

### CODE REVIEW

**Comment by domenic** [comment]
I'm particularly curious if this matches implementations; I'd be a bit surprised if they all plumbed such a flag through all this way just for the IndexedDB case. Maybe they do something less intrusive that the spec could copy.

**Comment by annevk** [comment]
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/indexeddb/IDBEventDispatcher.cpp seems like a specialized implementation of event dispatch for Indexed DB, but even there I cannot find a throwing reference. @inexorabletash? (Not reusing `EventTarget` might lead to other interesting bugs I suppose.)

@smaug---- what does Gecko do here?

**Comment by inexorabletash** [comment]
> Indexed Database API could have done with some architectural design review.

Are we taking the TARDIS or the Delorean this time? :)

-----

Blink has [EventTarget::uncaughtExceptionInEventHandler]( https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/events/EventTarget.h?dr&l=152) called from the [bindings code that calls event listeners/handlers](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/bindings/core/v8/V8AbstractEventListener.cpp?dr&l=144) - the only non-empty implementation is for Indexed DB's [IDBRequest](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/indexeddb/IDBRequest.cpp?dr&l=508)

The specialized dispatch is just used for the propagation logic, since the spec language for "get the parent" doesn't map to common code in Blink between the DOM and IDB. The actual firing/EventTarget code is common, though.

**Comment by smaug----** [comment]
Gecko has also special code added to event dispatch just because of IDB being weird. bent and sicking were happy about it at that time.

The actual event dispatch code is the same everywhere, it is just that IDB is the only one to check whether exception was thrown.

**Comment by domenic** [comment]
Sounds to me that in general like what implementations do is not much nicer than this spec patch, so probably fine as-is. But @annevk maybe you feel inspired by the above descriptions and can think of something a bit nicer.

**Comment by annevk** [comment]
The only other thing I could think of that would be cleaner was changing the return value, but that's much more invasive, especially just for IDB. A set of steps on `EventTarget` objects that only IDB uses might not be too bad though. @inexorabletash if I invoke a set of steps there when I see an exception that would be enough to fix this in IDB? What if multiple listeners throw?

**Comment by inexorabletash** [comment]
I'll need to test in implementations. The PR I just put up differs from Blink implementation in that it only looks at the flag after the dispatch is complete, whereas Blink aborts the transaction after the first callback that throws (so which would be in the "inner invoke" steps). In other words, throwing in the first listener would change state before the event made it to the second listener. 

(I suspect changing that would be web-compatible, but need tests anyway.)

**Comment by inexorabletash** [comment]
Re: _I'll need to test in implementations._

Gecko behaves per the [spec PR](https://github.com/w3c/IndexedDB/pull/149), looking at the flag after dispatch is complete. Blink looks at the flag after each handler is called, and only on the handlers on the request (not the "parent" for cases with propagation). I'll fix Blink to align with Gecko and the [spec PR](https://github.com/w3c/IndexedDB/pull/149).

**Comment by annevk** [comment]
It would be kind of nice to enforce that invariant, but that would require changing the return value of dispatch which seems quite disruptive. Also, given the prefix "legacy" hopefully nobody else starts using this.

**Comment by inexorabletash** [comment]
BTW, in case it wasn't clear: I'm happy with this PR as-is.

**Comment by annevk** [comment]
Thanks, hopefully "legacy" and the IDB-only note are enough of a tell for editors of new standards.

**Pull request merged**
