### PR TITLE
Add StaticRange constructor

### PR DESCRIPTION
**Pull request by sanketj**
Adding a constructor to the StaticRange interface. The shape of the constructor is based on how it is defined here: https://w3c.github.io/staticrange/index.html#interface-staticrange, and the construction algorithm is written based on the discussions here: #590 .

Also adding a section mentioning the high cost of maintaining ranges, and that static ranges are not subject to this cost because they do not update when the DOM tree mutates.

Corresponding WPT tests PR: https://github.com/web-platform-tests/wpt/pull/18619

***
<a href="https://whatpr.org/dom/778.html" title="Last updated on Aug 26, 2019, 12:27 PM UTC (17f27b2)">Preview</a> | <a href="https://whatpr.org/dom/778/a257369...17f27b2.html" title="Last updated on Aug 26, 2019, 12:27 PM UTC (17f27b2)">Diff</a>

### CODE REVIEW

**Comment by rniwa** [comment]
I've posted a WebKit patch on https://bugs.webkit.org/show_bug.cgi?id=201055.

**Comment by annevk** [comment]
Thanks! I wonder if we should make it a bit more friendly. Default `startOffset` to 0 (this can be done in IDL), default `endContainer` to `startContainer`, and default `endOffset` to `endContainer`'s child nodes length (perhaps only if `endContainer` is `startContainer`).

**Comment by annevk** [comment]
Also, please add your name to the Acknowledgments section.

**Comment by rniwa** [comment]
>  I wonder if we should make it a bit more friendly. Default startOffset to 0 (this can be done in IDL), default endContainer to startContainer, and default endOffset to endContainer's child nodes length (perhaps only if endContainer is startContainer).

We can make those changes too but I think this is a good first cut. I'll land the WebKit change anyway since that seems like more of an enhancement.

**Comment by sanketj** [comment]
> Also, please add your name to the Acknowledgments section.

Thanks, added! :)

**Comment by sanketj** [comment]
> > I wonder if we should make it a bit more friendly. Default startOffset to 0 (this can be done in IDL), default endContainer to startContainer, and default endOffset to endContainer's child nodes length (perhaps only if endContainer is startContainer).
> 
> We can make those changes too but I think this is a good first cut. I'll land the WebKit change anyway since that seems like more of an enhancement.

I tend to agree. Having some default values seems useful, but it might be better to wait and observe some patterns in StaticRange constructor usage before deciding on what those defaults should be.

**Comment by annevk** [comment]
Okay, that approach is fine with me. I pushed a number of editorial nits I'd appreciate your review on.

**Comment by annevk** [comment]
Thanks again @sanketj, please do return with more PRs 😊

**Comment by sanketj** [comment]
> Thanks again @sanketj, please do return with more PRs 😊

Thanks @annevk for the guidance and merging the PRs! Thanks @rniwa for the review! And yes, hopefully there will be more in the future. :)

**Comment by foolip** [comment]
https://dom.spec.whatwg.org/ wasn't updated after this was merged, see https://travis-ci.org/whatwg/dom/builds/578197397. That's because "a new promise" is ambiguous, which I saw another issue for but can't find now.

Should we work around this so we can get the live spec updated?

**Comment by foolip** [comment]
Hmm, fixed by https://github.com/w3ctag/promises-guide/pull/61, now that just has to propagate through... Shepherd?

**Comment by foolip** [comment]
Looks like it was https://github.com/tabatkins/bikeshed-data that needed an update, see https://github.com/tabatkins/bikeshed-data/issues/3. I pushed an update, then `bikeshed update` + `make local` works for DOM. I'll restart the Travis build to see if it'll deploy now.

**Comment by annevk** [comment]
Thanks, all good now.

**Pull request merged**
