### PR TITLE
Fix #146: Only run adopting steps when changing documents

### LINKED ISSUE #146: Only run "adopting steps" if oldDocument !== document
https://dom.spec.whatwg.org/#concept-node-adopt-ext

> For each descendant in node’s inclusive descendants, in tree order, run the adopting steps with descendant and oldDocument\.

@jdm found in https://github.com/w3c/web-platform-tests/issues/2466 that this doesn't have the intended behavior for `img` -- it's intended to rerun "update the image data" when the `img` changes node document, but not when it's moved around in the same document (except when moved into or out of a `picture`).

https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations

@annevk suggested in \#whatwg

> perhaps the "adopting steps" should only run if the document actually changes (and otherwise you just get the removal notification)

This would fix `img` and wouldn't regress `template`, AFAICT.

Thoughts?

cc @yoavweiss @smaug---- @domenic

### PR DESCRIPTION
**Pull request by zcorpan**
This doesn't change the rest of the "adopt" steps.

dom.html not included.

Issue: #146

### CODE REVIEW

**Comment by annevk** [comment]
I think it would be better to make step 3 and 4 substeps of a new step 3 that does that comparison and then runs the substeps, if necessary.

**Comment by zcorpan** [comment]
Done.

**Comment by annevk** [comment]
I cannot merge this until @tabatkins fixes bikeshed. It's become a big whack-a-mole game.

**Comment by annevk** [comment]
Thank you, committed as https://github.com/whatwg/dom/commit/bb69d0b0b280bf283550f2c21cabd0e6aa1d4cfc.

**Comment by annevk** [comment]
Oh, realized just now you created a local branch I could have rebased. Sorry.

**Pull request closed without merging**
