### PR TITLE
Shadow: Add "retargeting steps" to the dispatch algorithm

### LINKED ISSUE #286: Upstream Touch Events retargeting
See http://w3c.github.io/webcomponents/spec/shadow/#touch-events-retargeting.

This is the last part of the "Events" section in Shadow DOM spec, which we have not upstreamed to the DOM Standard (and/or Touch Events spec).

### PR DESCRIPTION
**Pull request by hayatoito**
Fix #286. Add the minimum hook to an event dispatch so other
specifications, such as TouchEvents spec, can retarget the event's
attributes, before invoking an event.

### CODE REVIEW

**Comment by hayatoito** [comment]
@annevk could you review this PR?

@RByers FYI.

**Comment by annevk** [comment]
Do we only need this for touch events? Or do we expect this to become more widely used?

**Comment by annevk** [comment]
I also don't really like using "attributes" since what we really want them to adjust are the internal slots and IDL still needs to become less vague on that whole subject. Maybe we can make it "retargeting steps" and define it in the same way we define other hooks like that (e.g., "removing steps")?

**Comment by hayatoito** [comment]
This is only for touch events, as of now.

"retargeting steps" sounds good. Let me update the PR.

**Comment by hayatoito** [comment]
I have updated the PR. Could you take a look?

**Comment by annevk** [comment]
Thank you! (I recommend updating your copy of bikeshed (git pull; bikeshed update).)

**Pull request merged**
