### PR TITLE
Run latest bikeshed

### PR DESCRIPTION
**Pull request by RByers**
I just ran `curl https://api.csswg.org/bikeshed/ -F file=@dom.bs > dom.html` without making any changes to the .bs file.  I figure you probably want this landed independently from any actual spec changes, right?

### CODE REVIEW

**Comment by annevk** [comment]
Yeah, this is #65 and per http://krijnhoetmer.nl/irc-logs/whatwg/20150904#l-678 there's other regressions. I recommend just patching `dom.bs` for now.

**Comment by RByers** [comment]
The spacing issue is now fixed (and it's pretty annoying IMHO).  From a quick glance at the [new output](https://rawgit.com/RByers/dom/bikeshed-update/dom.html) it looks like a net improvement to me.  Worth landing?

**Comment by annevk** [comment]
Did you look at the link I posted? I don't want to suddenly reference UI Events for classes that are defined by DOM.

**Comment by RByers** [comment]
Oh sorry, I missed that.  Ok, I'll leave this alone and submit patches only against the bs file for now (but maybe host a version of the html with my changes elsewhere in case people want to see it).

**Comment by annevk** [comment]
That sounds great!

**Pull request closed without merging**
