### PR TITLE
fix minor typo

### PR DESCRIPTION
**Pull request by WesNetmo**

### CODE REVIEW

**Comment by annevk** [comment]
Thank you, how would you like to be mentioned in the acknowledgments section?

**Comment by WesNetmo** [comment]
thank you for asking, but i will wait for something more significant :D

**Comment by annevk** [comment]
Up to you, but just so you know, we add folks to that section for less. 😊

Anyway, thank you!

**Comment by WesNetmo** [comment]
rofl. well, if that's the case, my name is Giorgio Liscio :)
and thank _you_ for your work. each line of a spec is one more year for a frontend developer to live :D

**Pull request closed without merging**
