### PR TITLE
Add the ability for an EventTarget to provide an algorithm to override

### PR DESCRIPTION
**Pull request by dtapuska**
the default passive value of AddEventListenerOptions.

Fixes issue #365

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 15, 2021, 7:33 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Fdom%2F8eb68e48b3f613663425120edc5039d83b3a9de8%2Fdom.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20366)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20whatwg/dom%23366.)._
</details>

### CODE REVIEW

**Comment by sahel-sh** [comment]
The test is added for the intervention:
https://github.com/web-platform-tests/wpt/blob/master/dom/events/document-level-wheel-event-listener-passive-by-default-manual.html

**Comment by annevk** [comment]
@dtapuska it seems that Safari ships something similar and Firefox is also planning on shipping this. Would you mind updating this PR with https://github.com/whatwg/dom/blob/master/PULL_REQUEST_TEMPLATE.md filled in? I suspect a forced rebase also wouldn't hurt to see about conflicts and trigger more recent bots.

**Comment by annevk** [comment]
Thanks @sahel-sh for the test. Do you know if there are tests for the body/html elements as well as the `Window` object? Also, it seems that with https://web-platform-tests.org/writing-tests/testdriver.html we might be able to automate these?

**Comment by domfarolino** [comment]
With https://github.com/whatwg/dom/pull/1087 merged, can this PR be closed?

**Comment by annevk** [comment]
Yeah, thanks for triaging.

**Pull request closed without merging**
