### PR TITLE
Editorial: add missing coma in attachShadow

### PR DESCRIPTION
**Pull request by pmdartus**
***
<a href="https://whatpr.org/dom/681.html" title="Last updated on Nov 4, 2019, 9:22 AM UTC (5f7b4c4)">Preview</a> | <a href="https://whatpr.org/dom/681/7a48d64...5f7b4c4.html" title="Last updated on Nov 4, 2019, 9:22 AM UTC (5f7b4c4)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
@pmdartus this is still relevant, no?

**Comment by annevk** [comment]
@jakearchibald did something got refactored in service workers? Any advice?

**Comment by annevk** [comment]
I'm gonna try land https://github.com/whatwg/dom/pull/653 first and then rebase.

**Comment by pmdartus** [comment]
Thank you for taking care of this PR @annevk.

**Comment by annevk** [comment]
Glad we *finally* fixed this comma issue!

**Pull request merged**
