### PR TITLE
Meta: export event listener's fields

### PR DESCRIPTION
**Pull request by domenic**
***
<a href="https://whatpr.org/dom/632.html" title="Last updated on Apr 10, 2018, 11:43 PM GMT (7b1ee4e)">Preview</a> | <a href="https://whatpr.org/dom/632/c80e017...7b1ee4e.html" title="Last updated on Apr 10, 2018, 11:43 PM GMT (7b1ee4e)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
Maybe don't export removed?

**Comment by domenic** [comment]
You still need to set it when creating a new event listener to pass to "add an event listener", don't you?

Although, I ended up not using this for async-local-storage after all, so we can close this until there's a real consumer.

**Comment by annevk** [comment]
No, because there's default values. You need to set the type and callback though.

I'd support exporting (minus removed) since HTML already uses type/callback, but I'm also fine with waiting for a Bikeshed consumer.

**Comment by domenic** [comment]
Right, I forgot about those. I'll close for now...

**Pull request closed without merging**
