### PR TITLE
Add attribute validate steps.

### PR DESCRIPTION
**Pull request by koto**
When [handling attribute change](https://dom.spec.whatwg.org/#handle-attribute-changes), validate the value before setting it. 

Attribute [append](https://dom.spec.whatwg.org/#concept-element-attributes-append) now also takes a value, and sets it only after handling the changes (this should be side-effects free, as no callbacks in handle attribute change get passed the attribute node - whose value is not yet set).

See #789 for the background. This PR doesn't allow the validate steps to change the value, only to possibly reject setting it.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 15, 2021, 7:33 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fkoto%2Fdom%2Fcc379857acc3a5b05eff9f64ca5ec9f989913332%2Fdom.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20809)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20whatwg/dom%23809.)._
</details>

### CODE REVIEW

**Comment by koto** [comment]
Rebased now that #805 is merged.

**Comment by koto** [comment]
From my pov this is ready for a review, see discussion in #789.

**Comment by koto** [comment]
Friendly ping, this seems to be the most efficient way we can prevent [attribute node bypasses](https://github.com/w3c/webappsec-trusted-types/issues/47) in Trusted Types by rejecting the value without potentially calling the default policy on all attr mutations.

**Comment by annevk** [comment]
I think this makes sense, but we should add a note explaining this setup somewhere close to where it's relevant.

**Comment by lukewarlow** [comment]
This should have implementor interest now given Mozilla's positive standards position on trusted types as a whole.

**Comment by annevk** [comment]
I think the main reason it wasn't merged was because it was abandoned.

I do wonder if we want an arbitrary extension point for this or just call into Trusted Types directly. With an arbitrary extension point we have the risk of running into ordering issues so we tend to avoid those these days, even though the DOM has some precedent for it (mainly historical).

**Comment by annevk** [comment]
That's not really an issue, especially for integration points. And in fact, we tend to prefer referencing the latest editor's draft.

**Comment by domenic** [comment]
Definite +1 for a direct call out.

**Comment by koto** [comment]
https://github.com/whatwg/dom/pull/1247 and https://github.com/w3c/trusted-types/pull/418 supercede this one. Unfortunately handling the attr mutation in DOM happens now after setting the new value, so I had to add an explicit new step to the algorithms.

**Pull request closed without merging**
