### PR TITLE
Remove 'passive' from the event listener key

### PR DESCRIPTION
**Pull request by RByers**
Fixes WICG/EventListenerOptions#27

### CODE REVIEW

**Comment by RByers** [comment]
Looks like the verison of bikeshed being served by api.csswg.org is resulting in some accidental changes (some linking seems broken).  So I undid the html changes and includes only the BS changes here.

**Comment by annevk** [comment]
Landed as https://github.com/whatwg/dom/commit/a13a3c7fc14732691b50c51316b16de0915a61f2. I had to make a couple of additional changes since you "forgot" that passive moved to a new dictionary (that might be some of the broken linkage you saw).

Glad it's all good now (with passive).

**Comment by RByers** [comment]
Oh shoot, sorry I missed that - thanks for fixing!  The broken linking was elsewhere, but I probably missed the warnings in the stream of other unrelated warnings :-(

**Comment by annevk** [comment]
Yeah, bunch of events are not indexed. I decided to live with it for now, sorry it made things harder.

**Pull request closed without merging**
