### PR TITLE
Meta: update repository files

### PR DESCRIPTION
**Pull request by foolip**
See https://github.com/whatwg/spec-factory for details.

### CODE REVIEW

**Comment by annevk** [comment]
This doesn't seem to work yet, right? Travis CI spun up and the "Checks" tab above is empty.

**Comment by foolip** [comment]
Hmm, the usual trick of closing and reopening worked. While GitHub Actions isn't 100% reliable, in web-platform-tests I have found it to trigger more reliably than Travis did, so I wouldn't take this as a red flag. It's plausible that there's something about the very first action run in a repo that makes this more likely, too.

**Comment by foolip** [comment]
I'll change the branch protection rules and merge this one now. (Weekend leisure activity.)

**Comment by foolip** [comment]
Success: https://dom.spec.whatwg.org/

**Pull request merged**
