### PR TITLE
Update element.attributes getter steps to be less vague

### PR DESCRIPTION
**Pull request by lukewarlow**
The getter steps were previously quite vague simply referring to "the associated NamedNodeMap" rather than referencing the attribute list concept.

- [ ] At least two implementers are interested (and none opposed):
   * …
   * …
- [ ] [Tests](https://github.com/web-platform-tests/wpt) are written and can be reviewed and commented upon at:
   * … 
- [ ] [Implementation bugs](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) are filed:
   * Chromium: …
   * Gecko: …
   * WebKit: …
   * Deno (only for aborting and events): …
   * Node.js (only for aborting and events): …
- [ ] [MDN issue](https://github.com/whatwg/meta/blob/main/MAINTAINERS.md#handling-pull-requests) is filed: …
- [ ] The top of this comment includes a [clear commit message](https://github.com/whatwg/meta/blob/main/COMMITTING.md) to use. 

(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)

***
<a href="https://whatpr.org/dom/1297.html" title="Last updated on Jul 19, 2024, 9:53 PM UTC (1d17b70)">Preview</a> | <a href="https://whatpr.org/dom/1297/abaa3fb...1d17b70.html" title="Last updated on Jul 19, 2024, 9:53 PM UTC (1d17b70)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
I agree that it's a bit vague and can be better, but this is incorrect. A node's attribute list is a list, not a NamedNodeMap.

**Comment by lukewarlow** [comment]
https://dom.spec.whatwg.org/#concept-element-attribute

> [Elements](https://dom.spec.whatwg.org/#concept-element) also have an attribute list, which is a [list](https://infra.spec.whatwg.org/#list) exposed through a [NamedNodeMap](https://dom.spec.whatwg.org/#namednodemap). Unless explicitly given when an [element](https://dom.spec.whatwg.org/#concept-element) is created, its [attribute list](https://dom.spec.whatwg.org/#concept-element-attribute) [is empty](https://infra.spec.whatwg.org/#list-is-empty).

I thought the exposed through a NamedNodeMap bit was enough? Or does the getter steps need to explicitly specify how to do that?

**Comment by lukewarlow** [comment]
Hmm looking a bit more https://dom.spec.whatwg.org/#namednodemap it seems that the NamedNodeMap has an associated element, not the other way around as the getter is currently defined. But yeah it seems exposing the list directly is wrong.

There doesn't seem to be a spec way to make a namednode map from an attribute list? Would `return this's attribute list as a NamedNodeMap` work? Or does it need to be more precise? It's at least a little bit clearer than currently?

**Comment by annevk** [comment]
To make it explicit you would define an element's associated **attribute object** (a NamedNodeMap) and then return that when appropriate.

**Comment by lukewarlow** [comment]
I'm gonna close this as I don't think it's going to be particularly clearer after any change I make

**Pull request closed without merging**
