### PR TITLE
Let DOMTokenList's add() return false when there are no supported tokens

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/whatwg/dom/issues/111

### CODE REVIEW

**Comment by foolip** [comment]
Not patching `dom.html` because the latest Bikeshed also causes other spurious changes, so you do it :)

@yoavweiss, please review and say if you'd be OK with doing this in Blink.

**Comment by yoavweiss** [comment]
I'd be OK with implementing assuming that this is the right way to go. I currently disagree about that, but let's discuss on the issue :)

**Comment by yoavweiss** [comment]
I believe that as defined in this PR, it would also result with `add()` never actually adding tokens to DOMTokenList without "supported tokens"

**Comment by annevk** [comment]
This is now #114 I assume?

**Comment by foolip** [comment]
Yes, I'll close my issue and PR.

**Comment by foolip** [comment]
Just this PR, actually.

**Pull request closed without merging**
