### PR TITLE
Use Boilerplate: omit feedback-header to remove redundant GitHub link

### PR DESCRIPTION
**Pull request by foolip**
This makes the output when running bikeshed locally match the current
dom.html output.

### CODE REVIEW

**Comment by annevk** [comment]
But I run bikeshed locally too. That's what gets checked in... Is there something else different?

**Comment by foolip** [comment]
Do you not get any diff other than the changed date? I get this:
```diff
--- a/dom.html
+++ b/dom.html
@@ -69,9 +69,11 @@
   <div class="head">
    <p data-fill-with="logo"><a class="logo" href="https://whatwg.org/"> <img alt="WHATWG" height="100" src="https://resources.whatwg.org/logo-dom.svg"> </a> </p>
    <h1 class="p-name no-ref allcaps" id="title">DOM</h1>
-   <h2 class="no-num no-toc no-ref heading settled" id="subtitle"><span class="content">Living Standard — Last Updated <time class="dt-updated" datetime="2015-09-16">16 September 2015</time></span></h2>
+   <h2 class="no-num no-toc no-ref heading settled" id="subtitle"><span class="content">Living Standard — Last Updated <time class="dt-updated" datetime="2015-09-17">17 September 2015</time></span></h2>
    <div data-fill-with="spec-metadata">
     <dl>
+     <dt>Issue Tracking:
+     <dd><a href="https://github.com/whatwg/dom/issues/">GitHub</a>
      <dt>Participate:
      <dd><span><a href="https://github.com/whatwg/dom">GitHub whatwg/dom</a> (<a href="https://github.com/whatwg/dom/issues/new">new issue</a>, <a href="https://github.com/whatwg/dom/issues">open issues</a>, <a href="https://www.w3.org/Bugs/Public/buglist.cgi?component=DOM&amp;product=WebAppsWG&amp;resolution=---">legacy open bugs</a>)</span>
      <dd><span><a href="https://wiki.whatwg.org/wiki/IRC">IRC: #whatwg on Freenode</a></span>
```

Bikeshed does some automatic detection of GitHub repos, and I note that it doesn't work if the name of the remote isn't origin, so that seems like the most likely difference in setup.

I did the same fix in https://github.com/whatwg/mediasession/commit/d79b4452c6c80b08001287a2c1418bd00af1bd46

**Comment by annevk** [comment]
I don't get this, no.

**Comment by foolip** [comment]
What is your output of `git remote -v`?

**Comment by annevk** [comment]
For bikeshed: 
```
origin	https://github.com/tabatkins/bikeshed.git (fetch)
origin	https://github.com/tabatkins/bikeshed.git (push)
```
For whatwg/dom:
```
origin	https://github.com/whatwg/dom.git (fetch)
origin	https://github.com/whatwg/dom.git (push)
```

**Comment by foolip** [comment]
My origin is `git@github.com:whatwg/dom.git`, if you use that you'll see the Issue Track section in the output. I can verify that `https://github.com/whatwg/dom.git` doesn't cause it to appear.

@tabatkins, is it a bug that only one of these forms is recognized as a GitHub repo?

In any event, I think my change fixes a problem :)

**Comment by annevk** [comment]
I cannot fix this at the moment since bikeshed overrides my `<dfn>`s with stuff from UI Events. This Shepherd setup is somewhat frustrating.

**Comment by foolip** [comment]
Yeah, I'm seeing the same thing after updating. Annoying, and I guess the dependencies aren't tracked by Git so you can't roll back while it's being fixed. Have you filed a bug somewhere?

**Comment by annevk** [comment]
The way to file a bug is to bug either @tabatkins or @plinss. I guess now I've bugged both.

**Comment by tabatkins** [comment]
Yeah, dealing with it now.  Sorry, I was sick most of last week in a way that made me only want to play videogames on the couch. >_<

**Comment by tabatkins** [comment]
Okay, fuck it, for now I've just made all non-partial interfaces automatically become `<dfn>`s.  This *will* change in the near future, when I add proper support for marking obsoletion of definitions, so watch for that.  Follow https://github.com/tabatkins/bikeshed/issues/321 for notifications of known breaking changes.

**Comment by tabatkins** [comment]
@foolip: Oh, and it is a Bikeshed bug that https origins aren't recognized by Bikeshed; it only knows about SSH urls.  I'll file a bug on myself and fix at some point.

**Pull request closed without merging**
