### PR TITLE
Specify CharacterData interface instead of implementers

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
As you can tell by the commit message and description, I hastily committed this just to get initial reactions

**Comment by annevk** [comment]
I think this is fine. @Ms2ger? It does seem that we could do this in more places. If we go ahead with this.

**Comment by Ms2ger** [comment]
Don't feel strongly either way.

**Comment by domenic** [comment]
I kind of liked having the switch only be over real node types, not including abstract base classes. But I don't feel strongly.

**Comment by annevk** [comment]
True, we should either go all the way everywhere or just only use the "real" classes.

**Comment by annevk** [comment]
I guess we'll leave this as is for now.

**Pull request closed without merging**
