### PR TITLE
Hyperlink "get the parent" in override defs for easier x-referencing

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by annevk** [comment]
Thank you, I need to wait for @tabatkins to fix bikeshed first.

**Comment by cvrebert** [comment]
Ah, https://github.com/tabatkins/bikeshed/issues/609, I see.

**Comment by annevk** [comment]
https://github.com/tabatkins/bikeshed/issues/610. Had not filed it, but now I have.

**Comment by annevk** [comment]
Thank you, landed as https://github.com/whatwg/dom/commit/a71b88d03939645ca5d73aa14b693d2db651b656.

**Pull request closed without merging**
