### PR TITLE
Fix #119: Merge DOMSettableTokenList into DOMTokenList

### LINKED ISSUE #119: Merge DOMSettableTokenList into DOMTokenList
Per discussion on IRC with @domenic and @zcorpan only HTML uses these classes. It seems like we could simplify things a bit by merging them into a single class and use `[PutForward]` everywhere.

The problem I could see is that libraries depend on changing the prototype of these classes in ways that are incompatible with such a simplification. What do folks think?

### PR DESCRIPTION
**Pull request by zcorpan**
Move DOMSettableTokenList#value to DOMTokenList and remove the
DOMSettableTokenList interface.

Issue: #119

### CODE REVIEW

**Comment by annevk** [comment]
@foolip @bzbarsky, any concerns?

**Comment by foolip** [comment]
From the spec point-of-view this makes sense to me, one can already change the underlying value using `DOMTokenList.prototype.add()`, so also being able to set `value` ought not introduce any new problems in principle.

Implementation-wise, a potential problem is that `DOMTokenList` is actually a virtual base class, with concrete subclasses `ClassList` (not an IDL interface) and `DOMSettableTokenList`. Without actually trying to write the code, it's hard to say if merging these into a single internal representation would cause any trouble, like maybe perf regressions for `classList`.

**Comment by bzbarsky** [comment]
> Implementation-wise, a potential problem is that DOMTokenList is actually a virtual base class

In Chrome. In Firefox it's not, for what it's worth.  Note that per spec there are currently `DOMTokenList`s that are neither `Element.classes` nor `DOMSettableTokenList`, though it looks like Chrome simply doesn't implement them.

I don't think there are any implementation issues here from Gecko's point of view.

What there _is_ is that the HTML spec needs to be updated in sync with this change, as do web platform tests.

**Comment by zcorpan** [comment]
@bzbarsky the HTML PR is https://github.com/whatwg/html/pull/361

Not PR for wpt yet, but I could look into that. https://github.com/w3c/web-platform-tests/issues/2411

**Comment by annevk** [comment]
I would like to hear from @foolip or someone else working on Blink before doing this. It seems totally like the thing I want us to be doing, but I don't want to upset anyone in the process.

**Comment by foolip** [comment]
I asked @yoavweiss if he wanted to work on this and it seemed like *maybe* he would. Thoughts? Investigating this properly in Blink amounts to trying to implement the change, and I have a few things too many in the air right now.

**Comment by yoavweiss** [comment]
I can try to implement it locally next week and see what happens.

**Comment by annevk** [comment]
@yoavweiss any updates?

**Comment by yoavweiss** [comment]
Not yet. Got postponed to post-holidays. Hope to get to it soon.

**Comment by yoavweiss** [comment]
A blink patch is at https://codereview.chromium.org/1629403003/

**Comment by zcorpan** [comment]
`classList` should have `[PutForwards=value]` in this PR; will fix.

**Comment by zcorpan** [comment]
Rebased and added `PutForwards`. (Bikeshed picks the wrong `value` to xref in the IDL block, but it's not a fatal error, just a warning. https://github.com/tabatkins/bikeshed/issues/582)

**Comment by annevk** [comment]
@zcorpan what's your preferred way of doing this? Should we just land this and see if browsers follow and hope there's no problem?

**Comment by zcorpan** [comment]
Yeah that seems reasonable to me since @yoavweiss has implemented it for blink already, it seems like it should work out OK. I can file bugs for other browsers also.

**Comment by annevk** [comment]
Thank you all!

**Comment by zcorpan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1244328
https://bugs.webkit.org/show_bug.cgi?id=153677
https://connect.microsoft.com/IE/feedbackdetail/view/2299283/merge-domtokenlist-and-domsettabletokenlist

**Pull request merged**
