### PR TITLE
Make Element's slot attributes Unscopable

### LINKED ISSUE #328: Make Element's slot attributes Unscopable
See https://bugs.chromium.org/p/chromium/issues/detail?id=643869#c19 for the context.

We might want to make Element's slot attributes Unscopable.

### PR DESCRIPTION
**Pull request by hayatoito**
Fixes #328.

### CODE REVIEW

**Comment by hayatoito** [comment]
In my local environment, it looks dom.html could have a lot of unrelated diffs if I try to generate dom.html.
Thus, I have not included dom.html in this PR. Is that okay?

**Comment by annevk** [comment]
Yeah, that's fine. 

@inscriber @rniwa @travisleithead you want to pick up this change too.

**Comment by annevk** [comment]
@hayatoito I think you need to update pygments (`pip install --upgrade pygments`).

**Comment by annevk** [comment]
Or maybe I needed to do that. Hmm. Done now.

**Pull request merged**
